---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
  labels:
    app: gomessage
    component: broadcaster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gomessage
      component: broadcaster
  template:
    metadata:
      labels:
        app: gomessage
        component: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: rmeharg/broadcaster
          args:
            - "-multicast"
            - "239.0.0.0:9002"
            #- "-count"
            #- "100"
            - "-duplicate"
            - "true"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener
  labels:
    app: gomessage
    component: listener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gomessage
      component: listener
  template:
    metadata:
      labels:
        app: gomessage
        component: listener
    spec:
      containers:
        - name: listener
          image: rmeharg/listener
          args:
            - "-amqp"
            - "amqp://user:CHANGEME@rabbitmq.rabbitmq.svc.cluster.local:5672"
            - "-multicast"
            - "239.0.0.0:9002"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoder
  labels:
    app: gomessage
    component: decoder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gomessage
      component: decoder
  template:
    metadata:
      labels:
        app: gomessage
        component: decoder
    spec:
      containers:
        - name: decoder
          image: rmeharg/decoder
          args:
            - "-amqp"
            - "amqp://user:CHANGEME@rabbitmq.rabbitmq.svc.cluster.local:5672"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
  labels:
    app: gomessage
    component: wrtier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gomessage
      component: writer
  template:
    metadata:
      labels:
        app: gomessage
        component: writer
    spec:
      containers:
        - name: writer
          image: rmeharg/writer
          args:
            - "-amqp"
            - "amqp://user:CHANGEME@rabbitmq.rabbitmq.svc.cluster.local:5672"
            - "-influxdb"
            - "http://influxdb-enterprise-data.influxdb.svc.cluster.local:8086"
            - "-influxdb-authtoken"
            - "admin:admin"
            - "-clickhouse"
            - "tcp://default:default@clickhouse-distributed.clickhouse.svc.cluster.local:9000?debug=true"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporter
  labels:
    app: gomessage
    component: reporter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gomessage
      component: reporter
  template:
    metadata:
      labels:
        app: gomessage
        component: reporter
    spec:
      containers:
        - name: reporter
          image: rmeharg/reporter
          args:
            - "-influxdb"
            - "http://influxdb-enterprise-data.influxdb.svc.cluster.local:8086"
            - "-influxdb-authtoken"
            - "admin:admin"
            - "s3"
            - "minio-s3.minio-s3.svc.cluster.local:9000"
            - "s3-accesskey-id"
            - "admin"
            - "s3-accesskey-secret"
            - "admin1234"
            - "s3-bucket"
            - "myreports"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
