apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: gomessage
build:
  artifacts:
    - image: rmeharg/broadcaster
      context: broadcaster
    - image: rmeharg/listener
      context: listener
    - image: rmeharg/decoder
      context: decoder
    - image: rmeharg/writer
      context: writer
    - image: rmeharg/reporter
      context: reporter
deploy:
  kubectl:
    manifests:
      - .ci/deployment.yaml
