apiVersion: v1
kind: Service
metadata:
  name: {{ include "conveyor.fullname" . }}-consumer
  labels:
    {{- include "conveyor.labels" . | nindent 4 }}
    component: consumer
spec:
  type: {{ .Values.consumer.service.type }}
  ports:
    - port: {{ .Values.consumer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "conveyor.selectorLabels" . | nindent 4 }}
    component: consumer
