apiVersion: v1
kind: Service
metadata:
  name: {{ include "conveyor.fullname" . }}-producer
  labels:
    {{- include "conveyor.labels" . | nindent 4 }}
    component: producer
spec:
  type: {{ .Values.producer.service.type }}
  ports:
    - port: {{ .Values.producer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "conveyor.selectorLabels" . | nindent 4 }}
    component: producer
