apiVersion: v1
kind: Service
metadata:
  name: gomessage
  labels:
    app: gomessage
spec:
  ports:
  - port: 8080
    protocol: TCP
  clusterIP: None
  selector:
    app: gomessage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomessage
  labels:
    app: gomessage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gomessage
  template:
    metadata:
      labels:
        app: gomessage
    spec:
      containers:
      - name: gomessage
        image: gomessage
