apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: gomessage
build:
  artifacts:
    - image: broadcaster
      context: broadcaster
    - image: listener
      context: listener
    - image: decoder
      context: decoder
    - image: writer
      context: writer
    - image: reporter
      context: reporter
deploy:
  kubectl:
    manifests:
      - ci/deployment.yaml
