apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: gomessage
build:
  artifacts:
  - image: gomessage
    docker:
      dockerfile: ci/Dockerfile
deploy:
  kubectl:
    manifests:
    - ci/deployment.yaml
portForward:
- resourceType: service
  resourceName: gomessage
  port: 8080
